/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as TicketsEventIdRouteImport } from './routes/tickets.$eventId'
import { Route as RegisterEventIdRouteImport } from './routes/register.$eventId'
import { Route as AppTicketsRouteImport } from './routes/app.tickets'
import { Route as AppSuperadminRouteImport } from './routes/app.superadmin'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppRegistrationsRouteImport } from './routes/app.registrations'
import { Route as AppExportRouteImport } from './routes/app.export'
import { Route as AppDonationsRouteImport } from './routes/app.donations'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'
import { Route as AppBudgetRouteImport } from './routes/app.budget'
import { Route as AppEventsIndexRouteImport } from './routes/app.events.index'
import { Route as AppEventsEventIdRouteImport } from './routes/app.events.$eventId'

const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TicketsEventIdRoute = TicketsEventIdRouteImport.update({
  id: '/tickets/$eventId',
  path: '/tickets/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterEventIdRoute = RegisterEventIdRouteImport.update({
  id: '/register/$eventId',
  path: '/register/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperadminRoute = AppSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistrationsRoute = AppRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppDonationsRoute = AppDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/donations': typeof AppDonationsRoute
  '/app/export': typeof AppExportRoute
  '/app/registrations': typeof AppRegistrationsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/superadmin': typeof AppSuperadminRoute
  '/app/tickets': typeof AppTicketsRoute
  '/register/$eventId': typeof RegisterEventIdRoute
  '/tickets/$eventId': typeof TicketsEventIdRoute
  '/app/': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/': typeof AppEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/donations': typeof AppDonationsRoute
  '/app/export': typeof AppExportRoute
  '/app/registrations': typeof AppRegistrationsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/superadmin': typeof AppSuperadminRoute
  '/app/tickets': typeof AppTicketsRoute
  '/register/$eventId': typeof RegisterEventIdRoute
  '/tickets/$eventId': typeof TicketsEventIdRoute
  '/app': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events': typeof AppEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/donations': typeof AppDonationsRoute
  '/app/export': typeof AppExportRoute
  '/app/registrations': typeof AppRegistrationsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/superadmin': typeof AppSuperadminRoute
  '/app/tickets': typeof AppTicketsRoute
  '/register/$eventId': typeof RegisterEventIdRoute
  '/tickets/$eventId': typeof TicketsEventIdRoute
  '/app/': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/': typeof AppEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/lookup'
    | '/app/budget'
    | '/app/checkin'
    | '/app/donations'
    | '/app/export'
    | '/app/registrations'
    | '/app/schedule'
    | '/app/superadmin'
    | '/app/tickets'
    | '/register/$eventId'
    | '/tickets/$eventId'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/lookup'
    | '/app/budget'
    | '/app/checkin'
    | '/app/donations'
    | '/app/export'
    | '/app/registrations'
    | '/app/schedule'
    | '/app/superadmin'
    | '/app/tickets'
    | '/register/$eventId'
    | '/tickets/$eventId'
    | '/app'
    | '/app/events/$eventId'
    | '/app/events'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/lookup'
    | '/app/budget'
    | '/app/checkin'
    | '/app/donations'
    | '/app/export'
    | '/app/registrations'
    | '/app/schedule'
    | '/app/superadmin'
    | '/app/tickets'
    | '/register/$eventId'
    | '/tickets/$eventId'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  LookupRoute: typeof LookupRoute
  RegisterEventIdRoute: typeof RegisterEventIdRoute
  TicketsEventIdRoute: typeof TicketsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/tickets/$eventId': {
      id: '/tickets/$eventId'
      path: '/tickets/$eventId'
      fullPath: '/tickets/$eventId'
      preLoaderRoute: typeof TicketsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$eventId': {
      id: '/register/$eventId'
      path: '/register/$eventId'
      fullPath: '/register/$eventId'
      preLoaderRoute: typeof RegisterEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/superadmin': {
      id: '/app/superadmin'
      path: '/superadmin'
      fullPath: '/app/superadmin'
      preLoaderRoute: typeof AppSuperadminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registrations': {
      id: '/app/registrations'
      path: '/registrations'
      fullPath: '/app/registrations'
      preLoaderRoute: typeof AppRegistrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/export': {
      id: '/app/export'
      path: '/export'
      fullPath: '/app/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/donations': {
      id: '/app/donations'
      path: '/donations'
      fullPath: '/app/donations'
      preLoaderRoute: typeof AppDonationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budget': {
      id: '/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRoute
  AppCheckinRoute: typeof AppCheckinRoute
  AppDonationsRoute: typeof AppDonationsRoute
  AppExportRoute: typeof AppExportRoute
  AppRegistrationsRoute: typeof AppRegistrationsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSuperadminRoute: typeof AppSuperadminRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRoute,
  AppCheckinRoute: AppCheckinRoute,
  AppDonationsRoute: AppDonationsRoute,
  AppExportRoute: AppExportRoute,
  AppRegistrationsRoute: AppRegistrationsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSuperadminRoute: AppSuperadminRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  LookupRoute: LookupRoute,
  RegisterEventIdRoute: RegisterEventIdRoute,
  TicketsEventIdRoute: TicketsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
